[pytest]
pythonpath = .
testpaths = tests
addopts = -ra --strict-markers
filterwarnings =
    ignore::DeprecationWarning:websockets.*
    ignore::DeprecationWarning:ollama.*

[coverage:run]
branch = True
source = .
omit =
    */tests/*
    setup.py
    */site-packages/*
    */.*

[coverage:report]
exclude_lines =
    pragma: no cover
    def __repr__
    raise AssertionError
    raise NotImplementedError
    if __name__ == .__main__.:
    if TYPE_CHECKING:
    @abstract
